[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  VITE_OPENROUTER_API_KEY = "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"
  VITE_OPENROUTER_MODEL = "openai/gpt-oss-120b:free"
  VITE_OPENROUTER_BASE_URL = "https://openrouter.ai/api/v1"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200