[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  VITE_GEMINI_API_KEY = "AIzaSyANh4_36zj4gDKFeCPi0xI_7NqBt-pZFGg"
  VITE_GEMINI_MODEL = "gemini-2.0-flash"
  VITE_GEMINI_BASE_URL = "https://generativelanguage.googleapis.com/v1beta"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200