[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Environment variables should be set in the Netlify dashboard
# VITE_OPENROUTER_API_KEY = "your_openrouter_api_key_here"
# VITE_OPENROUTER_MODEL = "x-ai/grok-4-fast:free"
# VITE_OPENROUTER_BASE_URL = "https://openrouter.ai/api/v1"