[build]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

# Firebase Configuration (Set these in Netlify dashboard)
VITE_FIREBASE_API_KEY = "your_firebase_api_key_here"
VITE_FIREBASE_AUTH_DOMAIN = "your-project.firebaseapp.com"
VITE_FIREBASE_PROJECT_ID = "your-project-id"
VITE_FIREBASE_STORAGE_BUCKET = "your-project.appspot.com"
VITE_FIREBASE_MESSAGING_SENDER_ID = "your_sender_id"
VITE_FIREBASE_APP_ID = "your_app_id"

# Google Gemini AI Configuration (Set these in Netlify dashboard)
VITE_GEMINI_API_KEY = "your_gemini_api_key_here"
VITE_GEMINI_MODEL = "gemini-2.0-flash-exp"
VITE_GEMINI_BASE_URL = "https://generativelanguage.googleapis.com/v1beta"

# OpenRouter AI Configuration (Set these in Netlify dashboard)
VITE_OPENROUTER_API_KEY = "your_openrouter_api_key_here"
VITE_OPENROUTER_MODEL = "google/gemini-2.0-flash-exp:free"
VITE_OPENROUTER_BASE_URL = "https://openrouter.ai/api/v1"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "netlify/functions"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"