/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "lzuwgoefuskxjaggmcev";
export const publicAnonKey =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx6dXdnb2VmdXNreGphZ2dtY2V2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU5NjkwOTIsImV4cCI6MjA3MTU0NTA5Mn0.p_BYZVqaZl9NBZrKYs9MGq27vvZjyEQJwh7y1n3NIDk";