import { createClient } from '@supabase/supabase-js'
// Get Supabase credentials from environment variables or the autogenerated info file
import { projectId, publicAnonKey } from '../../utils/supabase/info'

const supabaseUrl = `https://${projectId}.supabase.co`
const supabaseAnonKey = publicAnonKey

// Create a single Supabase client instance for the frontend
export const supabase = createClient(supabaseUrl, supabaseAnonKey)

export type SupabaseClient = typeof supabase